from pathlib import Path
import active_adaptation.utils.symmetry as symmetry_utils

from active_adaptation.assets.asset_cfg_bak import (
    AssetCfg,
    InitialStateCfg,
    ActuatorCfg,
    ContactSensorCfg,
)
from active_adaptation.registry import Registry

registry = Registry.instance()

FILE_DIR = Path(__file__).parent

ARMATURE_5020 = 0.003609725
ARMATURE_7520_14 = 0.010177520
ARMATURE_7520_22 = 0.025101925
ARMATURE_4010 = 0.00425

NATURAL_FREQ = 10 * 2.0 * 3.1415926535  # 10Hz
DAMPING_RATIO = 2.0

STIFFNESS_5020 = ARMATURE_5020 * NATURAL_FREQ**2
STIFFNESS_7520_14 = ARMATURE_7520_14 * NATURAL_FREQ**2
STIFFNESS_7520_22 = ARMATURE_7520_22 * NATURAL_FREQ**2
STIFFNESS_4010 = ARMATURE_4010 * NATURAL_FREQ**2

DAMPING_5020 = 2.0 * DAMPING_RATIO * ARMATURE_5020 * NATURAL_FREQ
DAMPING_7520_14 = 2.0 * DAMPING_RATIO * ARMATURE_7520_14 * NATURAL_FREQ
DAMPING_7520_22 = 2.0 * DAMPING_RATIO * ARMATURE_7520_22 * NATURAL_FREQ
DAMPING_4010 = 2.0 * DAMPING_RATIO * ARMATURE_4010 * NATURAL_FREQ


G1_WAIST_UNLOCKED_CFG = AssetCfg( # no wrist pitch and yaw
    mjcf_path=FILE_DIR / "G1" / "mjcf" / "g1.xml",
    usd_path=FILE_DIR / "G1" / "waist_unlocked.usd",
    init_state=InitialStateCfg(
        pos=(0.0, 0.0, 0.85),
        joint_pos={
            ".*_hip_pitch_joint": -0.1,
            ".*_knee_joint": 0.3,
            ".*_ankle_pitch_joint": -0.2,
            # ".*_hip_pitch_joint": -0.28,
            # ".*_knee_joint": 0.669,
            # ".*_ankle_pitch_joint": -0.363,
            ".*_elbow_joint": 0.6,
            "left_shoulder_roll_joint": 0.2,
            "left_shoulder_pitch_joint": 0.2,
            "right_shoulder_roll_joint": -0.2,
            "right_shoulder_pitch_joint": 0.2,
            "waist_yaw_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_pitch_joint": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    self_collisions=False,
    actuators={
        "base_legs": ActuatorCfg(
            joint_names_expr=".*",
            effort_limit={
                ".*_hip_yaw_joint.*": 88.0,
                ".*_hip_roll_joint.*": 139.0,
                ".*_hip_pitch_joint.*": 88.0,
                ".*_knee.*": 139.0,
                ".*_ankle.*": 50,
                ".*_shoulder.*": 25,
                ".*_elbow.*": 25,
                ".*_wrist_roll_joint": 25.0,
                ".*_wrist_pitch_joint": 5.0,
                ".*_wrist_yaw_joint": 5.0,
                "waist.*": 50,
            },
            velocity_limit={
                ".*_hip_yaw_joint": 32.0,
                ".*_hip_roll_joint": 20.0,
                ".*_hip_pitch_joint": 32.0,
                ".*_knee_joint": 20.0,
                ".*_ankle.*": 37.0,
                "waist.*": 37.0,
                ".*_shoulder_pitch_joint": 37.0,
                ".*_shoulder_roll_joint": 37.0,
                ".*_shoulder_yaw_joint": 37.0,
                ".*_elbow_joint": 37.0,
                ".*_wrist_roll_joint": 37.0,
                ".*_wrist_pitch_joint": 22.0,
                ".*_wrist_yaw_joint": 22.0,
            },
            stiffness={
                ".*_hip_yaw_joint": STIFFNESS_7520_14 * 2.0,
                ".*_hip_roll_joint": STIFFNESS_7520_22,
                ".*_hip_pitch_joint": STIFFNESS_7520_14 * 4.0,
                ".*_knee_joint": STIFFNESS_7520_22,
                ".*ankle.*": 2.0 * STIFFNESS_5020,
                "waist.*": 2.0 * STIFFNESS_5020,
                ".*_shoulder_pitch_joint": STIFFNESS_5020,
                ".*_shoulder_roll_joint": STIFFNESS_5020,
                ".*_shoulder_yaw_joint": STIFFNESS_5020,
                ".*_elbow_joint": STIFFNESS_5020,
                ".*_wrist_roll_joint": STIFFNESS_5020,
                ".*_wrist_pitch_joint": STIFFNESS_4010,
                ".*_wrist_yaw_joint": STIFFNESS_4010,
            },
            damping={
                ".*_hip_pitch_joint": DAMPING_7520_14,
                ".*_hip_roll_joint": DAMPING_7520_22,
                ".*_hip_yaw_joint": DAMPING_7520_14,
                ".*_knee_joint": DAMPING_7520_22,
                ".*ankle.*": 2.0 * DAMPING_5020,
                "waist.*": 2.0 * DAMPING_5020,
                ".*_shoulder_pitch_joint": DAMPING_5020,
                ".*_shoulder_roll_joint": DAMPING_5020,
                ".*_shoulder_yaw_joint": DAMPING_5020,
                ".*_elbow_joint": DAMPING_5020,
                ".*_wrist_roll_joint": DAMPING_5020,
                ".*_wrist_pitch_joint": DAMPING_4010,
                ".*_wrist_yaw_joint": DAMPING_4010,
            },
            armature={
                ".*_hip_pitch_joint": ARMATURE_7520_14,
                ".*_hip_roll_joint": ARMATURE_7520_22,
                ".*_hip_yaw_joint": ARMATURE_7520_14,
                ".*_knee_joint": ARMATURE_7520_22,
                ".*ankle.*": 2.0 * ARMATURE_5020,
                "waist.*": 2.0 * ARMATURE_5020,
                ".*_shoulder_pitch_joint": ARMATURE_5020,
                ".*_shoulder_roll_joint": ARMATURE_5020,
                ".*_shoulder_yaw_joint": ARMATURE_5020,
                ".*_elbow_joint": ARMATURE_5020,
                ".*_wrist_roll_joint": ARMATURE_5020,
                ".*_wrist_pitch_joint": ARMATURE_4010,
                ".*_wrist_yaw_joint": ARMATURE_4010,
            },
            friction=0.01,
        ),
    },
    joint_symmetry_mapping=symmetry_utils.mirrored({
        "left_hip_pitch_joint": (1, "right_hip_pitch_joint"),
        "left_hip_roll_joint": (-1, "right_hip_roll_joint"),
        "left_hip_yaw_joint": (-1, "right_hip_yaw_joint"),
        "left_knee_joint": (1, "right_knee_joint"),
        "left_ankle_pitch_joint": (1, "right_ankle_pitch_joint"),
        "left_ankle_roll_joint": (-1, "right_ankle_roll_joint"),
        "waist_yaw_joint": (-1, "waist_yaw_joint"),
        "waist_roll_joint": (-1, "waist_roll_joint"),
        "waist_pitch_joint": (1, "waist_pitch_joint"),
        "left_shoulder_pitch_joint": (1, "right_shoulder_pitch_joint"),
        "left_shoulder_roll_joint": (-1, "right_shoulder_roll_joint"),
        "left_shoulder_yaw_joint": (-1, "right_shoulder_yaw_joint"),
        "left_elbow_joint": (1, "right_elbow_joint"),
        "left_wrist_roll_joint": (-1, "right_wrist_roll_joint"),
        "left_wrist_pitch_joint": (1, "right_wrist_pitch_joint"),
        "left_wrist_yaw_joint": (-1, "right_wrist_yaw_joint")
    }),
    spatial_symmetry_mapping=symmetry_utils.mirrored({
        "left_hip_pitch_link": "right_hip_pitch_link",
        "left_hip_roll_link": "right_hip_roll_link",
        "left_hip_yaw_link": "right_hip_yaw_link",
        "left_knee_link": "right_knee_link",
        "left_ankle_pitch_link": "right_ankle_pitch_link",
        "left_ankle_roll_link": "right_ankle_roll_link",
        "pelvis": "pelvis",
        "torso_link": "torso_link",
        "waist_yaw_link": "waist_yaw_link",
        "waist_roll_link": "waist_roll_link",
        "left_shoulder_pitch_link": "right_shoulder_pitch_link",
        "left_shoulder_roll_link": "right_shoulder_roll_link",
        "left_shoulder_yaw_link": "right_shoulder_yaw_link",
        "left_elbow_link": "right_elbow_link",
        "left_wrist_roll_link": "right_wrist_roll_link",
        "left_wrist_yaw_link": "right_wrist_yaw_link",
        "left_wrist_pitch_link": "right_wrist_pitch_link"
    }),
    sensors_isaaclab=[
        ContactSensorCfg(
            name="contact_forces",
            primary=".*",
            secondary=[],
            track_air_time=True,
            history_length=3
        ),
    ],
    sensors_mjlab=[
        ContactSensorCfg(
            name="contact_forces",
            primary=".*",
            secondary=[],
            track_air_time=True,
            history_length=3
        ),
    ],
    joint_names_isaac=[
        'left_hip_pitch_joint', 'right_hip_pitch_joint',
        'waist_yaw_joint',
        'left_hip_roll_joint', 'right_hip_roll_joint',
        'waist_roll_joint',
        'left_hip_yaw_joint', 'right_hip_yaw_joint',
        'waist_pitch_joint',
        'left_knee_joint', 'right_knee_joint',
        'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint',
        'left_ankle_pitch_joint', 'right_ankle_pitch_joint',
        'left_shoulder_roll_joint', 'right_shoulder_roll_joint',
        'left_ankle_roll_joint', 'right_ankle_roll_joint',
        'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint',
        'left_elbow_joint', 'right_elbow_joint',
        'left_wrist_roll_joint', 'right_wrist_roll_joint',
        'left_wrist_pitch_joint', 'right_wrist_pitch_joint',
        'left_wrist_yaw_joint', 'right_wrist_yaw_joint'
    ],
    body_names_isaac=[
        'pelvis',
        'left_hip_pitch_link', 'right_hip_pitch_link',
        'waist_yaw_link',
        'left_hip_roll_link','right_hip_roll_link',
        'waist_roll_link',
        'left_hip_yaw_link', 'right_hip_yaw_link',
        'torso_link',
        'left_knee_link', 'right_knee_link',
        'left_shoulder_pitch_link', 'right_shoulder_pitch_link',
        'left_ankle_pitch_link', 'right_ankle_pitch_link',
        'left_shoulder_roll_link', 'right_shoulder_roll_link',
        'left_ankle_roll_link', 'right_ankle_roll_link',
        'left_shoulder_yaw_link', 'right_shoulder_yaw_link',
        'left_elbow_link', 'right_elbow_link',
        'left_wrist_roll_link', 'right_wrist_roll_link',
        'left_wrist_pitch_link', 'right_wrist_pitch_link',
        'left_wrist_yaw_link', 'right_wrist_yaw_link'
    ],
)
registry.register("asset", "g1_waist_unlocked", G1_WAIST_UNLOCKED_CFG)

GR3_CFG = AssetCfg(
    urdf_path=FILE_DIR / "GR3" / "gr3_fourier_hand_6dof.urdf",
    usd_path=FILE_DIR / "GR3" / "gr3_fourier_hand_6dof.usd",  # Note: may need to create USD file
    use_urdf_in_isaac=True,
    init_state=InitialStateCfg(
        pos=(0.0, 0.0, 0.70),
        joint_pos={
            ".*_hip_pitch_joint": -0.112,
            ".*_knee_pitch_joint": 0.369,
            ".*_ankle_pitch_joint": -0.263,
            ".*_elbow_pitch_joint": -0.3,
            "left_shoulder_roll_joint": 0.1,
            "left_shoulder_pitch_joint": 0.1,
            "right_shoulder_roll_joint": -0.1,
            "right_shoulder_pitch_joint": 0.1,
            "waist_yaw_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_pitch_joint": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    self_collisions=False,
    actuators={
        "base_legs": ActuatorCfg(
            joint_names_expr=".*",
            effort_limit={
                ".*_hip_yaw_joint.*": 88.0,
                ".*_hip_roll_joint.*": 139.0,
                ".*_hip_pitch_joint.*": 88.0,
                ".*_knee_pitch_joint.*": 139.0,
                ".*_ankle.*": 50.0,
                ".*_shoulder.*": 25.0,
                ".*_elbow_pitch_joint.*": 25.0,
                ".*_wrist_roll_joint": 25.0,
                ".*_wrist_pitch_joint": 5.0,
                ".*_wrist_yaw_joint": 5.0,
                "waist.*": 50.0,
            },
            velocity_limit={
                ".*_hip_yaw_joint": 32.0,
                ".*_hip_roll_joint": 20.0,
                ".*_hip_pitch_joint": 32.0,
                ".*_knee_pitch_joint": 20.0,
                ".*_ankle.*": 37.0,
                "waist.*": 37.0,
                ".*_shoulder_pitch_joint": 37.0,
                ".*_shoulder_roll_joint": 37.0,
                ".*_shoulder_yaw_joint": 37.0,
                ".*_elbow_pitch_joint": 37.0,
                ".*_wrist_roll_joint": 37.0,
                ".*_wrist_pitch_joint": 22.0,
                ".*_wrist_yaw_joint": 22.0,
            },
            stiffness={
                ".*_hip_yaw_joint": STIFFNESS_7520_14,
                ".*_hip_roll_joint": STIFFNESS_7520_22,
                ".*_hip_pitch_joint": STIFFNESS_7520_14,
                ".*_knee_pitch_joint": STIFFNESS_7520_22,
                ".*ankle.*": 2.0 * STIFFNESS_5020,
                "waist.*": 2.0 * STIFFNESS_5020,
                ".*_shoulder_pitch_joint": STIFFNESS_5020,
                ".*_shoulder_roll_joint": STIFFNESS_5020,
                ".*_shoulder_yaw_joint": STIFFNESS_5020,
                ".*_elbow_pitch_joint": STIFFNESS_5020,
                ".*_wrist_roll_joint": STIFFNESS_5020,
                ".*_wrist_pitch_joint": STIFFNESS_4010,
                ".*_wrist_yaw_joint": STIFFNESS_4010,
            },
            damping={
                ".*_hip_pitch_joint": DAMPING_7520_14,
                ".*_hip_roll_joint": DAMPING_7520_22,
                ".*_hip_yaw_joint": DAMPING_7520_14,
                ".*_knee_pitch_joint": DAMPING_7520_22,
                ".*ankle.*": 2.0 * DAMPING_5020,
                "waist.*": 2.0 * DAMPING_5020,
                ".*_shoulder_pitch_joint": DAMPING_5020,
                ".*_shoulder_roll_joint": DAMPING_5020,
                ".*_shoulder_yaw_joint": DAMPING_5020,
                ".*_elbow_pitch_joint": DAMPING_5020,
                ".*_wrist_roll_joint": DAMPING_5020,
                ".*_wrist_pitch_joint": DAMPING_4010,
                ".*_wrist_yaw_joint": DAMPING_4010,
            },
            armature={
                ".*_hip_pitch_joint": ARMATURE_7520_14,
                ".*_hip_roll_joint": ARMATURE_7520_22,
                ".*_hip_yaw_joint": ARMATURE_7520_14,
                ".*_knee_pitch_joint": ARMATURE_7520_22,
                ".*ankle.*": 2.0 * ARMATURE_5020,
                "waist.*": 2.0 * ARMATURE_5020,
                ".*_shoulder_pitch_joint": ARMATURE_5020,
                ".*_shoulder_roll_joint": ARMATURE_5020,
                ".*_shoulder_yaw_joint": ARMATURE_5020,
                ".*_elbow_pitch_joint": ARMATURE_5020,
                ".*_wrist_roll_joint": ARMATURE_5020,
                ".*_wrist_pitch_joint": ARMATURE_4010,
                ".*_wrist_yaw_joint": ARMATURE_4010,
            },
            friction=0.01,
        ),
    },
    joint_symmetry_mapping=symmetry_utils.mirrored({
        "left_hip_pitch_joint": (1, "right_hip_pitch_joint"),
        "left_hip_roll_joint": (-1, "right_hip_roll_joint"),
        "left_hip_yaw_joint": (-1, "right_hip_yaw_joint"),
        "left_knee_pitch_joint": (1, "right_knee_pitch_joint"),
        "left_ankle_pitch_joint": (1, "right_ankle_pitch_joint"),
        "left_ankle_roll_joint": (-1, "right_ankle_roll_joint"),
        "waist_yaw_joint": (-1, "waist_yaw_joint"),
        "waist_roll_joint": (-1, "waist_roll_joint"),
        "waist_pitch_joint": (1, "waist_pitch_joint"),
        "left_shoulder_pitch_joint": (1, "right_shoulder_pitch_joint"),
        "left_shoulder_roll_joint": (-1, "right_shoulder_roll_joint"),
        "left_shoulder_yaw_joint": (-1, "right_shoulder_yaw_joint"),
        "left_elbow_pitch_joint": (1, "right_elbow_pitch_joint"),
        "left_wrist_roll_joint": (-1, "right_wrist_roll_joint"),
        "left_wrist_pitch_joint": (1, "right_wrist_pitch_joint"),
        "left_wrist_yaw_joint": (-1, "right_wrist_yaw_joint")
    }),
    spatial_symmetry_mapping=symmetry_utils.mirrored({
        "left_thigh_pitch_link": "right_thigh_pitch_link",
        "left_thigh_roll_link": "right_thigh_roll_link",
        "left_thigh_yaw_link": "right_thigh_yaw_link",
        "left_shank_pitch_link": "right_shank_pitch_link",
        "left_foot_pitch_link": "right_foot_pitch_link",
        "left_foot_roll_link": "right_foot_roll_link",
        "base_link": "base_link",
        "torso_link": "torso_link",
        "waist_yaw_link": "waist_yaw_link",
        "waist_roll_link": "waist_roll_link",
        "left_upper_arm_pitch_link": "right_upper_arm_pitch_link",
        "left_upper_arm_roll_link": "right_upper_arm_roll_link",
        "left_upper_arm_yaw_link": "right_upper_arm_yaw_link",
        "left_lower_arm_pitch_link": "right_lower_arm_pitch_link",
        "left_hand_yaw_link": "right_hand_yaw_link",
        "left_hand_pitch_link": "right_hand_pitch_link",
        "left_hand_roll_link": "right_hand_roll_link"
    }),
    sensors_isaaclab=[
        ContactSensorCfg(
            name="contact_forces",
            primary=".*",
            secondary=[],
            track_air_time=True,
            history_length=3
        ),
    ],
    sensors_mjlab=[
        ContactSensorCfg(
            name="contact_forces",
            primary=".*",
            secondary=[],
            track_air_time=True,
            history_length=3
        ),
    ],
    joint_names_isaac=[
        'left_hip_pitch_joint', 'right_hip_pitch_joint',
        'waist_yaw_joint',
        'left_hip_roll_joint', 'right_hip_roll_joint',
        'waist_roll_joint',
        'left_hip_yaw_joint', 'right_hip_yaw_joint',
        'waist_pitch_joint',
        'left_knee_pitch_joint', 'right_knee_pitch_joint',
        'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint',
        'left_ankle_pitch_joint', 'right_ankle_pitch_joint',
        'left_shoulder_roll_joint', 'right_shoulder_roll_joint',
        'left_ankle_roll_joint', 'right_ankle_roll_joint',
        'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint',
        'left_elbow_pitch_joint', 'right_elbow_pitch_joint',
        'left_wrist_roll_joint', 'right_wrist_roll_joint',
        'left_wrist_pitch_joint', 'right_wrist_pitch_joint',
        'left_wrist_yaw_joint', 'right_wrist_yaw_joint'
    ],
    body_names_isaac=[
        'base_link',
        'left_thigh_pitch_link', 'right_thigh_pitch_link',
        'waist_yaw_link',
        'left_thigh_roll_link', 'right_thigh_roll_link',
        'waist_roll_link',
        'left_thigh_yaw_link', 'right_thigh_yaw_link',
        'torso_link',
        'left_shank_pitch_link', 'right_shank_pitch_link',
        'left_upper_arm_pitch_link', 'right_upper_arm_pitch_link',
        'left_foot_pitch_link', 'right_foot_pitch_link',
        'left_upper_arm_roll_link', 'right_upper_arm_roll_link',
        'left_foot_roll_link', 'right_foot_roll_link',
        'left_upper_arm_yaw_link', 'right_upper_arm_yaw_link',
        'left_lower_arm_pitch_link', 'right_lower_arm_pitch_link',
        'left_hand_yaw_link', 'right_hand_yaw_link',
        'left_hand_pitch_link', 'right_hand_pitch_link',
        'left_hand_roll_link', 'right_hand_roll_link'
    ],
)
registry.register("asset", "gr3_fourier_hand_6dof", GR3_CFG)
